// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU-IOqN9tSUZ-ui5mPjqRd4uUkD3ba9uY',
    appId: '1:1003705856918:web:1146fa0bf29ebd4548e3b7',
    messagingSenderId: '1003705856918',
    projectId: 'constructionsitemanageme-8a45d',
    authDomain: 'constructionsitemanageme-8a45d.firebaseapp.com',
    storageBucket: 'constructionsitemanageme-8a45d.firebasestorage.app',
    measurementId: 'G-HMXGQWV6ZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfaMhe3LV6qW-5PsOcFR9lHpxazw1EDOg',
    appId: '1:1003705856918:android:0024a7b59df8e6b348e3b7',
    messagingSenderId: '1003705856918',
    projectId: 'constructionsitemanageme-8a45d',
    storageBucket: 'constructionsitemanageme-8a45d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGPRjC4NrtXK397buIerDhFTTslY6YuMY',
    appId: '1:1003705856918:ios:d46f0fce8056d16548e3b7',
    messagingSenderId: '1003705856918',
    projectId: 'constructionsitemanageme-8a45d',
    storageBucket: 'constructionsitemanageme-8a45d.firebasestorage.app',
    iosBundleId: 'com.example.sitemanagementapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGPRjC4NrtXK397buIerDhFTTslY6YuMY',
    appId: '1:1003705856918:ios:d46f0fce8056d16548e3b7',
    messagingSenderId: '1003705856918',
    projectId: 'constructionsitemanageme-8a45d',
    storageBucket: 'constructionsitemanageme-8a45d.firebasestorage.app',
    iosBundleId: 'com.example.sitemanagementapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU-IOqN9tSUZ-ui5mPjqRd4uUkD3ba9uY',
    appId: '1:1003705856918:web:4335a45a24fe60ea48e3b7',
    messagingSenderId: '1003705856918',
    projectId: 'constructionsitemanageme-8a45d',
    authDomain: 'constructionsitemanageme-8a45d.firebaseapp.com',
    storageBucket: 'constructionsitemanageme-8a45d.firebasestorage.app',
    measurementId: 'G-DBVWPRXYEV',
  );
}
